import type { GlobalThemeOverrides } from 'naive-ui';

export const lightOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#0052FF',
    primaryColorHover: '#0047DE',
    primaryColorPressed: '#0038B0',
    primaryColorSuppl: '#0052FF',
    infoColor: '#2563EB',
    successColor: '#16A34A',
    warningColor: '#F59E0B',
    errorColor: '#EF4444',
    bodyColor: '#FAFAFA',
    cardColor: '#FFFFFF',
    modalColor: '#FFFFFF',
    popoverColor: '#FFFFFF',
    tableColor: '#FFFFFF',
    tableColorHover: '#F6F9FF',
    tableColorStriped: '#FBFDFF',
    inputColor: '#FFFFFF',
    actionColor: '#F1F5F9',
    hoverColor: '#F1F5F9',
    borderColor: '#E2E8F0',
    dividerColor: '#E6EDF5',
    textColorBase: '#0F172A',
    textColor1: '#0F172A',
    textColor2: '#1E293B',
    textColor3: '#64748B',
    placeholderColor: '#94A3B8',
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    fontFamilyMono: "'JetBrains Mono', 'Consolas', monospace",
    borderRadius: '12px',
    borderRadiusSmall: '10px',
  },
  Button: {
    borderRadiusMedium: '12px',
    borderRadiusSmall: '10px',
    borderRadiusTiny: '8px',
    borderMedium: '1px solid #d4dfef',
    textColorTextPrimary: '#1f57cc',
    colorError: '#EF4444',
    colorErrorHover: '#DC2626',
    colorErrorPressed: '#B91C1C',
  },
  Card: {
    color: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: '16px',
  },
  DataTable: {
    thColor: '#F8FAFC',
    tdColor: '#FFFFFF',
    tdColorHover: '#F6F9FF',
    borderColor: '#E8EEF8',
    thTextColor: '#64748B',
    tdTextColor: '#0F172A',
    thFontWeight: '700',
    thPaddingSmall: '12px 12px',
    tdPaddingSmall: '12px 12px',
  },
  Input: {
    color: '#FFFFFF',
    colorFocus: '#FFFFFF',
    border: '1px solid #D6E1EE',
    borderHover: '1px solid #C1D2E8',
    borderFocus: '1px solid #0052FF',
    boxShadowFocus: '0 0 0 2px rgba(0, 82, 255, 0.16)',
  },
  Select: {
    peers: {
      InternalSelection: {
        color: '#FFFFFF',
        border: '1px solid #D6E1EE',
        borderHover: '1px solid #C1D2E8',
        borderActive: '1px solid #0052FF',
        borderFocus: '1px solid #0052FF',
      },
    },
  },
  Tabs: {
    tabTextColorActiveLine: '#1f57cc',
    barColor: '#0052FF',
    tabTextColorLine: '#64748B',
    tabTextColorHoverLine: '#1E293B',
  },
  Modal: {
    color: '#FFFFFF',
    borderRadius: '20px',
    padding: '24px',
    boxShadow: '0 20px 60px -24px rgba(15, 23, 42, 0.35)',
  },
  Dialog: {
    color: '#FFFFFF',
    borderRadius: '20px',
    padding: '24px',
    iconSize: '28px',
    iconColorWarning: '#0052FF',
    iconColorError: '#0052FF',
    iconColorInfo: '#2563EB',
    iconColorSuccess: '#16A34A',
    border: '1px solid rgba(0, 82, 255, 0.15)',
    boxShadow: '0 20px 60px -24px rgba(0, 82, 255, 0.25)',
  },
  Drawer: {
    color: '#F8FAFC',
    headerBorderBottom: '1px solid #E2E8F0',
    bodyPadding: '0',
  },
  Dropdown: {
    color: '#FFFFFF',
    optionColorHover: '#F1F5F9',
    borderRadius: '12px',
  },
  Tag: {
    borderRadius: '12px',
    colorInfo: '#dbeafe',
    colorInfoText: '#1e40af',
    colorSuccess: '#dcfce7',
    colorSuccessText: '#166534',
    colorWarning: '#fef3c7',
    colorWarningText: '#92400e',
    colorError: '#fee2e2',
    colorErrorText: '#991b1b',
  },
  Form: {
    labelTextColor: '#6d7f97',
  },
  Switch: {
    railColorActive: '#0052FF',
    boxShadowActive: '0 0 0 2px rgba(0, 82, 255, 0.15)',
  },
  Pagination: {
    itemBorderRadius: '10px',
    buttonBorderRadius: '10px',
  },
};

export const darkOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#4d7cff',
    primaryColorHover: '#6b93ff',
    primaryColorPressed: '#3366ff',
    primaryColorSuppl: '#4d7cff',
    infoColor: '#60a5fa',
    successColor: '#4ade80',
    warningColor: '#fbbf24',
    errorColor: '#f87171',
    bodyColor: '#0c0e14',
    cardColor: '#141620',
    modalColor: '#1a1d2b',
    popoverColor: '#1a1d2b',
    tableColor: '#141620',
    tableColorHover: '#1a1d2b',
    tableColorStriped: '#12141e',
    inputColor: '#141620',
    actionColor: '#1a1d2b',
    hoverColor: '#1e2233',
    borderColor: '#2a2e3e',
    dividerColor: '#252838',
    textColorBase: '#e2e8f0',
    textColor1: '#e2e8f0',
    textColor2: '#cbd5e1',
    textColor3: '#94a3b8',
    placeholderColor: '#64748b',
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    fontFamilyMono: "'JetBrains Mono', 'Consolas', monospace",
    borderRadius: '12px',
    borderRadiusSmall: '10px',
  },
  Button: {
    borderRadiusMedium: '12px',
    borderRadiusSmall: '10px',
    borderRadiusTiny: '8px',
    borderMedium: '1px solid #2a2e3e',
    textColorTextPrimary: '#6b93ff',
    colorError: '#f87171',
    colorErrorHover: '#ef4444',
    colorErrorPressed: '#dc2626',
  },
  Card: {
    color: '#141620',
    borderColor: '#2a2e3e',
    borderRadius: '16px',
  },
  DataTable: {
    thColor: '#12141e',
    tdColor: '#141620',
    tdColorHover: '#1a1d2b',
    borderColor: '#252838',
    thTextColor: '#94a3b8',
    tdTextColor: '#e2e8f0',
    thFontWeight: '700',
    thPaddingSmall: '12px 12px',
    tdPaddingSmall: '12px 12px',
  },
  Input: {
    color: '#141620',
    colorFocus: '#1a1d2b',
    border: '1px solid #2a2e3e',
    borderHover: '1px solid #3a3f52',
    borderFocus: '1px solid #4d7cff',
    boxShadowFocus: '0 0 0 2px rgba(77, 124, 255, 0.2)',
  },
  Select: {
    peers: {
      InternalSelection: {
        color: '#141620',
        border: '1px solid #2a2e3e',
        borderHover: '1px solid #3a3f52',
        borderActive: '1px solid #4d7cff',
        borderFocus: '1px solid #4d7cff',
      },
    },
  },
  Tabs: {
    tabTextColorActiveLine: '#6b93ff',
    barColor: '#4d7cff',
    tabTextColorLine: '#94a3b8',
    tabTextColorHoverLine: '#cbd5e1',
  },
  Modal: {
    color: '#1a1d2b',
    borderRadius: '20px',
    padding: '24px',
    boxShadow: '0 20px 60px -24px rgba(0, 0, 0, 0.6)',
  },
  Dialog: {
    color: '#1a1d2b',
    borderRadius: '20px',
    padding: '24px',
    iconSize: '28px',
    iconColorWarning: '#4d7cff',
    iconColorError: '#4d7cff',
    iconColorInfo: '#60a5fa',
    iconColorSuccess: '#4ade80',
    border: '1px solid rgba(77, 124, 255, 0.2)',
    boxShadow: '0 20px 60px -24px rgba(0, 0, 0, 0.5)',
  },
  Drawer: {
    color: '#12141e',
    headerBorderBottom: '1px solid #2a2e3e',
    bodyPadding: '0',
  },
  Dropdown: {
    color: '#1a1d2b',
    optionColorHover: '#252838',
    borderRadius: '12px',
  },
  Tag: {
    borderRadius: '12px',
    colorInfo: '#1e3a5f',
    colorInfoText: '#93c5fd',
    colorSuccess: '#14532d',
    colorSuccessText: '#86efac',
    colorWarning: '#451a03',
    colorWarningText: '#fcd34d',
    colorError: '#450a0a',
    colorErrorText: '#fca5a5',
  },
  Form: {
    labelTextColor: '#94a3b8',
  },
  Switch: {
    railColorActive: '#4d7cff',
    boxShadowActive: '0 0 0 2px rgba(77, 124, 255, 0.2)',
  },
  Pagination: {
    itemBorderRadius: '10px',
    buttonBorderRadius: '10px',
  },
};

/** @deprecated Use lightOverrides instead */
export const themeOverrides = lightOverrides;
